networks:
    nonsense:
        external: false

services:
    nonsense_db:
        extends:
            file: docker-compose.yml
            service: nonsense_db
        networks:
            - nonsense

    nonsense_api:
        extends:
            file: docker-compose.yml
            service: nonsense_api
        ports:
            - "${HTTP_PORT}:80"
        networks:
            - nonsense
