version: "3.5"

networks:
  canonhead:
    external: false

services:
    server:
        build: .
        container_name: canonhead_server
        networks:
            - canonhead
        volumes:
            - /var/canonhead:/data
        ports:
            - "${HTTP_PORT}:80"
