version: "3.5"

networks:
    nonsense:
        external: false

services:
    nonsense_db:
        image: mongo
        container_name: nonsense_db
        networks:
            - nonsense
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - /var/nonsense/db:/data/db

    nonsense_server:
        build: .
        image: nonsense_server
        container_name: nonsense_server
        networks:
            - nonsense
        volumes:
            - /var/nonsense/server:/data
            - /var/www/nonsense/thumbnails:/thumbnails
            - /var/www/nonsense/files:/files
        ports:
            - "${HTTP_PORT}:80"
        environment:
            - ADMIN_TOKEN=${ADMIN_TOKEN}
