version: "3.5"

networks:
  canonfire:
    external: false

services:
    server:
        build: server
        container_name: canonfire_server
        networks:
            - canonfire
        volumes:
            - /var/canonfire:/data
        ports:
            - "${HTTP_PORT}:80"
