networks:
    nonsense:
        external: false

services:
    nonsense_db:
        image: mongo
        container_name: nonsense_db
        networks:
            - nonsense
        restart: unless-stopped
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - /var/nonsense/db:/data/db

    nonsense_api:
        build: .
        image: nonsense_api
        container_name: nonsense_api
        networks:
            - nonsense
        volumes:
            - /var/nonsense/server:/data
            - /var/www/nonsense/thumbnails:/thumbnails
            - /var/www/nonsense/files:/files
        environment:
            - ADMIN_TOKEN=${ADMIN_TOKEN}

    nonsense_server:
        image: nginx
        container_name: nonsense_server
        ports:
            - "127.0.0.1:${HTTP_PORT}:80"
        networks:
            - nonsense
        volumes:
            - /var/www/nonsense:/var/www/nonsense
            - ./nginx.site:/etc/nginx/conf.d/default.conf
