version: "3.5"

networks:
    canonhead:
        external: false

services:
    server:
        build: .
        container_name: canonhead_server
        networks:
            - canonhead
        volumes:
            - /var/canonhead:/data
            - /var/www/canonhead/files:/files
        ports:
            - "${HTTP_PORT}:80"
