version: "3.5"

networks:
    nonsense:
        external: false

services:
    server:
        build: .
        image: nonsense_server
        container_name: nonsense_server
        networks:
            - nonsense
        volumes:
            - /var/nonsense/server:/data
            - /var/www/nonsense/files:/files
        ports:
            - "${HTTP_PORT}:80"
        environment:
            - ADMIN_TOKEN=${ADMIN_TOKEN}
