version: "3.5"

networks:
  townhall:
    external: false

services:
    server:
        build: server
        container_name: townhall_server
        networks:
            - townhall
        volumes:
            - /var/townhall:/data
        ports:
            - "${HTTP_PORT}:80"
