networks:
    nonsense:
        external: false

services:
    nonsense_db:
        image: mongo
        container_name: nonsense_db
        networks:
            - nonsense
        restart: unless-stopped
        volumes:
            - ${DATA_ROOT}/db:/data/db

    nonsense_api:
        build: .
        image: nonsense_api
        container_name: nonsense_api
        networks:
            - nonsense
        volumes:
            - ${DATA_ROOT}/server:/data
            - ${WEB_ROOT}/thumbnails:/thumbnails
            - ${WEB_ROOT}/files:/files
        environment:
            - ADMIN_TOKEN=${ADMIN_TOKEN}

    nonsense_server:
        image: nginx
        container_name: nonsense_server
        ports:
            - "127.0.0.1:${HTTP_PORT}:80"
        networks:
            - nonsense
        volumes:
            - ${WEB_ROOT}:/var/www/nonsense
            - ./nginx.site:/etc/nginx/conf.d/default.conf
